sudo: false
dist: bionic
addons:
  apt:
    packages:
    - latex-xcolor
    - texlive-base
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - texlive-formats-extra
    - texlive-bibtex-extra
    - texlive-humanities
    - texinfo
    - texlive-science
    - latexmk
    - lmodern
script:
- ./build-cv.sh
after_success:
- cat bibliography/*.bib > build/gkthiruvathukal-cv.bib
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - ./**/gkthiruvathukal-cv.pdf
    - ./**/gkthiruvathukal-cv.bib
  skip_cleanup: true
  on:
    repo: gkthiruvathukal/cv
    tags: true
